image:
  repository: public.ecr.aws/h8r7r9n6/jit-k8s-agent
  tag: 1.2.1
  pullPolicy: IfNotPresent

cluster:
  name: "" # Required, set it while installing the chart. Should be unique across all clusters.

jit:
  # Option 1: Direct credentials (required if existingSecret is not provided)
  clientId: "" # Set during installation when using direct credentials
  clientSecret: "" # Set during installation when using direct credentials
  # Option 2: Reference to existing secret (alternative to clientId/clientSecret)
  existingSecret: "" # Name of existing secret containing JIT_CLIENT_ID and JIT_CLIENT_SECRET
  apiUrl: https://api.jit.io

kubescape:
  enabled: true

serviceAccount:
  name: jit-k8s-agent-sa

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"

# Optional: Node selector for pod scheduling
nodeSelector: {}

# Optional: Tolerations for pod scheduling on tainted nodes
tolerations: []