image:
  repository: public.ecr.aws/h8r7r9n6/jit-k8s-agent
  tag: 1.2.1
  pullPolicy: IfNotPresent

cluster:
  name: "" # Required, set it while installing the chart. Should be unique across all clusters.

jit:
  # clientId and clientSecret are required when not using an existing secret
  # clientId: ""
  # clientSecret: ""
  # existingSecret prevents storing clientId and clientSecret as plain text in the values.yaml file
  # existingSecret: ""
  apiUrl: https://api.jit.io

kubescape:
  enabled: true

serviceAccount:
  name: jit-k8s-agent-sa

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"
