apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cronjob
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: OnFailure
          containers:
            - name: jit-k8s-collector
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: CLUSTER_NAME
                  value: {{ .Values.cluster.name }}
                - name: JIT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Chart.Name }}-jit-credentials
                      key: JIT_CLIENT_ID
                - name: JIT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Chart.Name }}-jit-credentials
                      key: JIT_CLIENT_SECRET
                - name: JIT_API_URL
                  value: {{ .Values.jit.apiUrl }}
